# Generated by Django 5.1.2 on 2024-10-31 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Basic', 'Basic'), ('Plus', 'Plus')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DecimalField(decimal_places=0, max_digits=2, max_length=31)),
                ('method', models.CharField(choices=[('PIX', 'PIX'), ('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=40)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.plan')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.plan'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CrossFit', 'CrossFit'), ('Fisioterapia', 'Fisioterapia'), ('Gap', 'Gap'), ('Musculação', 'Musculação')], max_length=40)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField(default='000/00/00', verbose_name='dd/mm/yyy')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.lecture')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.matricula')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payment')),
            ],
        ),
    ]
