# Generated by Django 5.1.2 on 2024-10-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_lecture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('Fisioterapia', 'Fisioterapia'), ('CrossFit', 'CrossFit'), ('Gap', 'Gap'), ('Musculação', 'Musculação')], max_length=40),
        ),
    ]
