# Generated by Django 5.1.2 on 2024-11-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_lecture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('CrossFit', 'CrossFit'), ('Musculação', 'Musculação'), ('Fisioterapia', 'Fisioterapia'), ('Gap', 'Gap')], max_length=40),
        ),
    ]
