# Generated by Django 5.1.2 on 2024-11-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_lecture_finish_time_lecture_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment',
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='user.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plans',
            field=models.ManyToManyField(to='user.plan'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('CrossFit', 'CrossFit'), ('Musculação', 'Musculação'), ('Gap', 'Gap'), ('Fisioterapia', 'Fisioterapia')], max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='0000-00-00', verbose_name='dd/mm/yyyy'),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
