# Generated by Django 5.1.2 on 2024-11-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_lecture_attended_remove_lecture_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='value',
        ),
    ]
