# Generated by Django 5.1.2 on 2024-11-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adm',
            field=models.BooleanField(default=False),
        ),
    ]
